[obs_connection]
host = <hostname or ip>
port = <port of Websocket server>
password = <password>

[influxdb_connection]
host = "<hostname or ip>"
port = 1234
token = "<token>"
org = "<some-org>"
bucket = "<some-bucket>"
