[influxdb_connection]
host = "localhost"
port = 1234
token = "<some-token>"
org = "some-org"
bucket = "some-bucket"

[session]
location = "some-location"
org = "some-org"
bucket = "some-bucket"
driver = "some-driver"
gender = "some-gender"
